const ON_APP_SHOW = "ON_APP_SHOW";
const ON_APP_HIDE = "ON_APP_HIDE";

const ON_JOIN_MEMBER_SUCCESS = "ON_JOIN_MEMBER_SUCCESS";
const ON_JOIN_MEMBER_FAIL = "ON_JOIN_MEMBER_FAIL";
const ON_JOIN_MEMBER_CLOSE = "ON_JOIN_MEMBER_CLOSE";
